sync with develop
aprehende/aprehende-cli-tool pull request #32
Opened 2023-05-31 19:42 UTC by jnadroj

2023-05-31 20:08 UTC, geamdev approved these changes
LGTM 💯

2023-05-31 20:12 UTC, joelgurumendi commented on src/generators/subcomponent.ts
> +  const componentsFolderPath = `${componentsPath}/Button`;
@TitoWin94  Change folder name Button to Example

2023-05-31 20:12 UTC, joelgurumendi commented on src/generators/subcomponent.ts
> +    componentName: "Button",
@TitoWin94  Change ComponentName Button to Example

2023-05-31 20:12 UTC, joelgurumendi commented on src/generators/subcomponent.ts
> +    componentName: "Button",
@TitoWin94 Change ComponentName Button to Example

2023-05-31 20:12 UTC, joelgurumendi commented on src/generators/subcomponent.ts
> +    `${componentsFolderPath}/Button.${extension}x`,
@TitoWin94 Change FileName Button to Example

2023-05-31 20:25 UTC, joelgurumendi requested changes
@TitoWin94 revisemos los comentarios

2023-05-31 20:25 UTC, joelgurumendi requested changes
@TitoWin94 revisemos los comentarios

2023-06-01 00:41 UTC, joelgurumendi approved these changes
LGTM 😄

2023-06-01 00:41 UTC, merged